name: 📝 Draft release changelog

on:
  workflow_dispatch:
    inputs:
      release_pr_number:
        description: "Previous Release PR Number"
        required: true
        default: ""
      tag:
        description: "Tag for release (manual input)"
        required: true
        default: ""

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: 📟 Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 📝 Release Drafter
        id: release-drafter
        uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348 # v6.0.0
        # with:
        #   config-name: platform-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 💾 Save Changelog
        run: |
          cat << 'EOF' > CHANGELOG.md
          ${{ steps.release-drafter.outputs.body }}
          EOF

      - name: 🧬 Process Changelog
        run: |
          pip install requests openai
          python .github/scripts/process_changelog.py CHANGELOG.md ${{ github.event.inputs.release_pr_number }}
          python .github/scripts/summarize_changelog.py ${{ secrets.GITHUB_TOKEN }} ${{ secrets.OPENAI_API_KEY }}
          cat CHANGELOG.md

      - name: 🛫 Create Release
        uses: mikepenz/action-gh-release@9a604afa5167a745eab07256a54e2f578a1a0c5e # v1
        with:
          body_path: "CHANGELOG.md"
          tag_name: ${{ github.event.inputs.tag }}
          prerelease: false
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
